version: '3'
services:
  web:
    build:
      context: ./
      args:
        - NPM_CONFIG_ENVATO_TOKEN
    links:
      - database
      - smtp
    volumes:
      - ./:/var/www/:cached
    command: 'sh -c "composer install -d /var/www && apache2-foreground"'
  cache:
    ports:
      - 8888:80
  database:
    image: mariadb:10.2
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  smtp:
    image: sj26/mailcatcher
    ports:
      - 1080:1080
volumes:
  db-data:
