version: '3'
services:
  web:
    restart: always
    networks:
      - default
      - database
    volumes:
      - files:/var/www/html/sites/default/files
      - tmp:/var/www/tmp
  cache:
    restart: always
    networks:
      - default
      - ingress
  cron:
    restart: always
networks:
  ingress:
    external:
      name: ingress
  database:
    external:
      name: database
