version: '3'
services:
  web:
    image: docker.pkg.github.com/phototech/suncoastsailingcharters/suncoastsailingcharters
    env_file:
      - .env
  cache:
    image: davidbarratt/varnish
    environment:
      VIRTUAL_HOST: suncoastsailingcharters.com,origin.suncoastsailingcharters.com,www.suncoastsailingcharters.com
      LETSENCRYPT_HOST: suncoastsailingcharters.com,origin.suncoastsailingcharters.com,www.suncoastsailingcharters.com
    links:
      - web:backend
  cron:
    image: davidbarratt/cron
    env_file:
      - .env
    links:
      - web
volumes:
  files:
  tmp:
